config/routes.rb
SimpleAutocompleteDemo::Application.routes.draw do
  resources :people do 
    get :autocomplete_for_person_name, :on => :collection
  end

  resource :person_finder, :only => :show do
    get :autocomplete_for_person_name
  end
  
  root :to => "people#index"
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  autocomplete_for :person, :name
  
  def index
    @people = Person.all
  end

  def new
    @person = Person.new
  end

  def edit
    @person = Person.find(params[:id])
  end

  def create
    @person = Person.new(params[:person])

    if @person.save
      redirect_to(people_path, :notice => 'Person was successfully created.')
    else
      render :action => "new"
    end
  end

  def update
    @person = Person.find(params[:id])

    if @person.update_attributes(params[:person])
      redirect_to(people_path, :notice => 'Person was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    redirect_to(people_url)
  end
end

app/controllers/person_finders_controller.rb
class PersonFindersController < ApplicationController
  autocomplete_for :person, :name
  
  def show
    found_person = Person.find_by_name(params[:name])
    if found_person
      redirect_to edit_person_path(found_person)
    else
      redirect_to people_path
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ :charset => "utf-8" }
    %title Simple_Autocomplete Demo
    = stylesheet_link_tag 'scaffold', 'jquery.autocomplete'
    = csrf_meta_tag

  %body
    %header
      %nav
        = link_to "List all People", people_path
        |
        = link_to "Create a new Person", new_person_path
        |
        %span
          = form_tag person_finder_path, :method => :get do
            = text_field_tag :name, "", :class => 'autocomplete', 'data-autocomplete-url' => autocomplete_for_person_name_people_path
            = submit_tag "Find Person"

      .flash
        - flash.each do |name, msg|
          = content_tag :div, msg, :id => "flash_#{name}", :class => "message"

    %article
      = yield

  = google_jquery
  = javascript_include_tag "jquery.autocomplete.js", "autocomplete-hook.js"

app/views/people/_form.html.haml
= form_for @person do |form|
  %section
    %h2= form.label :name, "Enter the name of the person"
    = form.text_field :name

  %section
    = form.submit

app/views/people/edit.html.haml
%h1 Editing Person
= render "form"

= button_to "Remove this person", person_path(@person), :method => :delete

app/views/people/index.html.haml
%h1 People

%ul
  - @people.each do |person|
    %li= link_to person.name, edit_person_path(person)

app/views/people/new.html.haml
%h1 Creating A New Person
= render "form"